# Generated by Django 3.0.4 on 2020-08-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200814_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
    ]
